'use client';
import {useEffect,useRef,useState} from 'react';import {ZoomIn,X,ChevronLeft,ChevronRight} from 'lucide-react';
const reviews=Array.from({length:12},(_,i)=>'/reviews/review-'+String(i+1).padStart(2,'0')+(i<10?'.jpg':'.jpeg'));
export default function ReviewsGallery(){const [expanded,setExpanded]=useState(false);const [selected,setSelected]=useState(0);const dialog=useRef(null);
useEffect(()=>{const el=dialog.current;const reset=()=>{document.body.style.overflow=''};el.addEventListener('close',reset);return()=>{el.removeEventListener('close',reset);reset()}},[]);
function open(i){setSelected(i);dialog.current.showModal();document.body.style.overflow='hidden'}
function step(n){setSelected(i=>(i+n+reviews.length)%reviews.length)}
return <section id="reviews" className="section reviews-section"><div className="container"><div className="section-heading"><span className="eyebrow">آراء أولياء الأمور وقصص النجاح</span><h2>رسائلهم تحكي <em>عن تجربتهم.</em></h2></div><div className="review-grid">{reviews.slice(0,expanded?12:6).map((src,i)=><button className="review-card" key={src} onClick={()=>open(i)} aria-label={'تكبير رأي ولي الأمر '+(i+1)}><img src={src} alt={'رسالة من آراء أولياء الأمور '+(i+1)} width="720" height="500" loading="lazy"/><span>آراء أولياء الأمور <ZoomIn size={17}/></span></button>)}</div><div className="review-actions"><button className="button outline" onClick={()=>setExpanded(!expanded)} aria-expanded={expanded}>{expanded?'عرض صور أقل':'عرض جميع الصور'}</button></div></div><dialog ref={dialog} className="lightbox" aria-label="معاينة آراء أولياء الأمور" onClick={e=>{if(e.target===dialog.current)dialog.current.close()}} onKeyDown={e=>{if(e.key==='ArrowLeft'){e.preventDefault();step(1)}if(e.key==='ArrowRight'){e.preventDefault();step(-1)}}}><div className="lightbox-head"><span>آراء أولياء الأمور</span><button onClick={()=>dialog.current.close()} aria-label="إغلاق المعاينة" autoFocus><X size={21}/></button></div><img src={reviews[selected]} alt={'رأي ولي الأمر '+(selected+1)}/><div className="lightbox-controls"><button onClick={()=>step(-1)} aria-label="الصورة السابقة"><ChevronRight/></button><span>{selected+1} / {reviews.length}</span><button onClick={()=>step(1)} aria-label="الصورة التالية"><ChevronLeft/></button></div></dialog></section>}

