import Link from 'next/link';
import {BookOpen,Heart,GraduationCap,Clock,Globe,Users,AudioLines,ArrowUpLeft,Sprout,Languages,NotebookPen,ShieldCheck} from 'lucide-react';
import ReviewsGallery from '../components/ReviewsGallery';
import {programs,about} from '../lib/content';
const icons=[BookOpen,AudioLines,Languages,GraduationCap,Sprout,NotebookPen];
const programImages=['/assets/generated/study-details.png','/assets/generated/learning-hero.png','/assets/generated/family-learning.png','/assets/generated/islamic-studies.png','/assets/generated/child-awareness.png','/assets/generated/school-subjects.png'];
const benefits=[[Heart,'تعليم فردي يناسب مستوى كل طالب'],[BookOpen,'تحفيظ القرآن الكريم مع تصحيح التلاوة والتجويد'],[GraduationCap,'معلمون ومعلمات متخصصون'],[ShieldCheck,'متابعة مستمرة وتقييم لمستوى الطالب'],[Users,'تواصل ومتابعة مع ولي الأمر'],[Clock,'مواعيد مرنة تناسب مختلف الدول والأوقات'],[Globe,'تعليم أونلاين من أي مكان في العالم'],[Sprout,'أسلوب تربوي يحفّز الطالب ويحببه في القرآن']];
export default function Home(){return <main id="main">
<section className="hero pattern"><div className="hero-glow" aria-hidden="true"/><div className="container hero-content"><span className="eyebrow"><span className="status-dot"/> أكادمية المنذر · تعليم أونلاين</span><h1>نربط قلوب أبنائنا <span>بكتاب الله</span></h1><p className="hero-description">نساعدهم على حفظه وفهمه والعمل به. تعليمٌ عصري وتربوي يناسب الأطفال والكبار، مع اهتمام حقيقي ومتابعة مستمرة لكل طالب.</p><div className="actions"><Link className="button gold" href="/contact">تواصل معنا <ArrowUpLeft size={19}/></Link><a className="button outline" href="#programs"><BookOpen size={19}/> البرامج والتخصصات</a></div><div className="hero-benefits"><span><ShieldCheck/> تعليم فردي</span><span><GraduationCap/> معلمون ومعلمات متخصصون</span><span><Clock/> مواعيد مرنة</span></div><div className="hero-motto">نتعلّم <span>✦</span> لنفهم <span>✦</span> لنرتقي</div></div></section>
<div className="age-band"><div className="container"><span>لكل الأعمار</span><span>أطفال ٤–٦ سنوات</span><span>أطفال ٧–١٢ سنة</span><span>مراهقون ١٣–١٧ سنة</span><span>بالغون ١٨+</span></div></div>
<section id="programs" className="section container"><div className="section-heading"><span className="eyebrow">البرامج والتخصصات</span><h2>العلم الذي ينفعه،<br/><em>والقرآن الذي يصحبه.</em></h2><p>القرآن الكريم، اللغة العربية، العلوم الشرعية، والتأسيس الدراسي.</p></div><div className="program-grid">{programs.map((p,i)=>{const Icon=icons[i];return <article className="program-card has-photo" key={p.title}>{<div className="program-photo"><img src={programImages[i]} alt="" width="1536" height="1024" loading="lazy"/></div>}<div className="card-top"><span className="icon-box"><Icon/></span><span className="card-number">0{i+1}</span></div><h3>{p.title}</h3><p>{p.description}</p><Link href="/contact" className="text-link">استفسر عن البرنامج <ArrowUpLeft size={18}/></Link></article>})}</div></section>
<section className="section why-section pattern" id="why-us"><div className="container"><div className="section-heading"><span className="eyebrow">لماذا أكادمية المنذر؟</span><h2>يحفظه في صدره، ويفهمه بعقله،<br/><em>ويعمل به في سلوكه وأخلاقه.</em></h2></div><div className="benefit-grid">{benefits.map(([Icon,title])=><article key={title} className="benefit"><Icon/><h3>{title}</h3></article>)}</div><blockquote>«لا نريد أن يحفظ ابنك القرآن فقط، بل نريد أن يصبح القرآن جزءًا من شخصيته وحياته.»</blockquote></div></section>
<section className="section container about-preview"><figure className="family-portrait"><img className="family-photo" src="/assets/generated/family-learning.png" alt="صورة توضيحية لأم تساند ابنتها أثناء التعلم أونلاين" width="1536" height="1024" loading="lazy"/><figcaption><Heart size={20}/><span>كل طالب… أمانة ومسؤولية</span></figcaption><span className="portrait-mark" aria-hidden="true">✦</span></figure><div><span className="eyebrow">من نحن</span><h2>كل طالب عندنا<br/><em>أمانة ومسؤولية.</em></h2><p>{about}</p><Link className="text-link" href="/about">تعرّف على أكادمية المنذر <ArrowUpLeft size={20}/></Link></div></section>
<ReviewsGallery/><section className="container closing"><BookOpen size={38}/><h2>أن يحب القرآن، ويتقنه، <em>ويعيش به.</em></h2><p>أن نجعل تعلم القرآن الكريم تجربة سهلة، ممتعة، مؤثرة، ومتاحة للجميع أينما كانوا.</p><Link className="button gold" href="/contact">تواصل مع الأكاديمية <ArrowUpLeft size={19}/></Link></section></main>}



